import React, { useEffect, useState } from 'react';
import { FlatList, Text, View, StyleSheet } from 'react-native';
import { ScreenShell } from '../components/ScreenShell';
import { LargeActionButton } from '../components/LargeActionButton';
import { driverApi } from '../api/driverApi';

export function HistoryScreen() {
  const [items, setItems] = useState([]);
  const [refreshing, setRefreshing] = useState(false);

  async function load() {
    setRefreshing(true);
    try {
      const response = await driverApi.getHistory();
      setItems(response.data?.items || []);
    } catch (error) {
      setItems([]);
    } finally {
      setRefreshing(false);
    }
  }

  useEffect(() => {
    load();
  }, []);

  return (
    <ScreenShell
      eyebrow="Verification Log"
      title="Transit Decision History"
      subtitle="Review the newest pass and hold outcomes generated by the demo."
      alignTop
    >
      <LargeActionButton
        label={refreshing ? 'Refreshing...' : 'Refresh History'}
        onPress={load}
        disabled={refreshing}
        variant="secondary"
      />
      <FlatList
        data={items}
        keyExtractor={(item) => item.scanId}
        renderItem={({ item }) => (
          <View style={styles.card}>
            <Text style={styles.main}>{item.packetCode}</Text>
            <Text style={styles.meta}>Decision: {item.decision}</Text>
            <Text style={styles.meta}>Status: {item.status}</Text>
            <Text style={styles.meta}>Action: {item.recommendedAction}</Text>
            <Text style={styles.meta}>Scanned: {new Date(item.scannedAt).toLocaleString()}</Text>
          </View>
        )}
        contentContainerStyle={styles.listContent}
        ListEmptyComponent={<Text style={styles.empty}>No verification history yet.</Text>}
      />
    </ScreenShell>
  );
}

const styles = StyleSheet.create({
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginBottom: 10,
    gap: 4,
  },
  listContent: {
    paddingTop: 12,
    paddingBottom: 24,
  },
  main: {
    fontSize: 18,
    fontWeight: '600',
    color: '#0F172A',
  },
  meta: {
    fontSize: 14,
    color: '#475569',
  },
  empty: {
    textAlign: 'center',
    fontSize: 18,
    color: '#64748B',
    marginTop: 24,
  },
});
